// <auto-generated />
using System;
using Final_Task.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Final_Task.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Final_Task.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SalesBuzz.Shared.Data.Auditing.AuditCriteria", b =>
                {
                    b.Property<int>("OperationType")
                        .HasColumnType("int");

                    b.Property<string>("TableFields")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("AuditCriteria");
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.BS_Periods", b =>
                {
                    b.Property<string>("YearId")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PeriodId")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("BUID")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Createdby")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("L1Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("L2Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<int>("PeriodKey")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("displayorder")
                        .HasColumnType("int");

                    b.HasKey("YearId", "PeriodId")
                        .HasName("PK_YearPeriods");

                    b.HasIndex(new[] { "PeriodKey" }, "UQ__BS_Periods__565DD247")
                        .IsUnique();

                    b.ToTable("BS_Periods");
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.BS_Years", b =>
                {
                    b.Property<string>("YearId")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("BUID")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Createdby")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("L1Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("L2Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("YearEndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("YearStartDate")
                        .HasColumnType("datetime");

                    b.HasKey("YearId")
                        .HasName("PK_Years");

                    b.ToTable("BS_Years");
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.HH_AR_SalesmenCats", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArabicDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommissionSchemeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("RecordSource")
                        .HasColumnType("tinyint");

                    b.Property<string>("buid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("HH_AR_SalesmenCats");
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.HH_AR_SalesmenPcts", b =>
                {
                    b.Property<string>("SalesmanId")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SubordinateId")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("BUID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("nchar(15)")
                        .HasDefaultValueSql("('1')")
                        .IsFixedLength();

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Createdby")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<byte?>("RecordSource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("Serial")
                        .HasColumnType("int");

                    b.HasKey("SalesmanId", "SubordinateId");

                    b.ToTable("HH_AR_SalesmenPcts", (string)null);
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.HH_Customer", b =>
                {
                    b.Property<string>("CustomerNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ActualAvg")
                        .HasColumnType("int");

                    b.Property<int?>("ActualNPS")
                        .HasColumnType("int");

                    b.Property<string>("AddAddressA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddAddressE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("AllowBankTransfer")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("AllowCash")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("AllowCheck")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("AllowCoupon")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("AllowCreditCard")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("AllowDebitCard")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("AllowDeferred")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("AllowEPayment")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("AllowInstallment")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("AllowTempCredit")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("Altitude")
                        .HasColumnType("numeric(24, 15)");

                    b.Property<string>("AreaNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("BadPayer")
                        .HasColumnType("tinyint");

                    b.Property<double?>("Balance")
                        .HasColumnType("float");

                    b.Property<string>("BusinessId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CashDiscountID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChannelID")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CityNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CloseTimeTW1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CloseTimeTW2")
                        .HasColumnType("datetime2");

                    b.Property<string>("CommerceChamberRegNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CommercialRegistrationDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CommercialRegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ConfirmedOrders")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ConsignmentProductRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContactType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditItemCriteria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CustomerNameA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerNameE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerServiceManNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerStatus")
                        .HasColumnType("int");

                    b.Property<string>("CustomerTradeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CutomerPhysicalLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultTerritory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryInvoiceProductRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistrictNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DueDateToleranceDays")
                        .HasColumnType("int");

                    b.Property<byte?>("EInvoiceCustomerType")
                        .HasColumnType("tinyint");

                    b.Property<string>("ElectricityNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailTemplateType")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("ErrorRadius")
                        .HasColumnType("int");

                    b.Property<byte?>("ForceCreditLimit")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("Fri")
                        .HasColumnType("bit");

                    b.Property<string>("GISCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("HasCreditControlArea")
                        .HasColumnType("tinyint");

                    b.Property<string>("HeadOfficeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Inactive")
                        .HasColumnType("tinyint");

                    b.Property<string>("InvoiceAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("IsHeadOffice")
                        .HasColumnType("tinyint");

                    b.Property<byte>("IsPhysicalLocation")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("IsPotential")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric(24, 15)");

                    b.Property<string>("LegacyCustomerAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegacyCustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric(24, 15)");

                    b.Property<byte?>("MandatoryPhoto")
                        .HasColumnType("tinyint");

                    b.Property<int?>("MerchType")
                        .HasColumnType("int");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Mon")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MunicipalLicenseDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MunicipalLicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NoOfAllowedRedeemPacks")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OpenTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OpenTimeTW1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OpenTimeTW2")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderCeiling")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OwnerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("PaymentMethod")
                        .HasColumnType("tinyint");

                    b.Property<int?>("PointsBalance")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PotCustomerRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("PreventSalesmanfromCollectingOutStandingInvoices")
                        .HasColumnType("tinyint");

                    b.Property<string>("PriceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductRangeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("ProofOfVisit")
                        .HasColumnType("tinyint");

                    b.Property<string>("RecommendedPriceID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("RecordSource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("RegionNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("RequireCheckPhoto")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("RequiresManualInvNo")
                        .HasColumnType("tinyint");

                    b.Property<string>("ResponsibleID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsibleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("ReturnType")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("ReturnWithoutInvoice")
                        .HasColumnType("tinyint");

                    b.Property<string>("RouteID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesDivisionID")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("SalesSectorNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesmanNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Sat")
                        .HasColumnType("bit");

                    b.Property<string>("ServicePatternSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceTimeTypeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("SharedCredit")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("SkipDueDateValidation")
                        .HasColumnType("tinyint");

                    b.Property<string>("StopComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StopDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StopDateTime")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("StopOrder")
                        .HasColumnType("tinyint");

                    b.Property<byte>("StopOutLimit")
                        .HasColumnType("tinyint");

                    b.Property<string>("StopReasonID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Sun")
                        .HasColumnType("bit");

                    b.Property<int?>("TargetAvg")
                        .HasColumnType("int");

                    b.Property<int?>("TargetNPS")
                        .HasColumnType("int");

                    b.Property<string>("TaxId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxRegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TempCreditItemCriteria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TempCreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TermsBranch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TermsId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Thu")
                        .HasColumnType("bit");

                    b.Property<bool?>("ToVisit")
                        .HasColumnType("bit");

                    b.Property<bool?>("Tue")
                        .HasColumnType("bit");

                    b.Property<byte?>("UnpaidInvoiceCustomerWarning")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("ValidateRecommendedQty")
                        .HasColumnType("tinyint");

                    b.Property<int?>("VisitFrequency")
                        .HasColumnType("int");

                    b.Property<int?>("VisitOrder")
                        .HasColumnType("int");

                    b.Property<bool?>("Wed")
                        .HasColumnType("bit");

                    b.Property<string>("WindowTypeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("WorkFLowStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("today")
                        .HasColumnType("int");

                    b.HasKey("CustomerNo");

                    b.ToTable("HH_Customer", null, t =>
                        {
                            t.HasTrigger("HH_Customer_insert_trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.HH_CustomerLocations", b =>
                {
                    b.Property<string>("CustomerNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("LineSerial")
                        .HasColumnType("int");

                    b.Property<Guid>("CustomerLocationsGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AssetID")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("AssetNO")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("BUID")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ContractDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ContractID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Createdby")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("Inactive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("InactiveDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<string>("LocationNo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ManufSerialNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<byte[]>("PlanoGramImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("RecordSource")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("TypeInfo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Year")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CustomerNo", "LineSerial", "CustomerLocationsGUID");

                    b.HasIndex(new[] { "LocationNo" }, "idx_HH_CustomerLocations_LocationNo");

                    b.ToTable("HH_CustomerLocations", t =>
                        {
                            t.HasTrigger("hh_customerLocations_InactiveDate_InsertTrigger");

                            t.HasTrigger("hh_customerLocations_InactiveDate_UpdateTrigger");

                            t.HasTrigger("hh_customerLocations_delete_trigger");

                            t.HasTrigger("hh_customerLocations_insert_trigger");

                            t.HasTrigger("hh_customerLocations_update_trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.HH_EntityBUControl", b =>
                {
                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("BUControl")
                        .HasColumnType("tinyint");

                    b.HasKey("TableName");

                    b.ToTable("HH_EntityBUControl");
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.HH_IC_UOMDetail", b =>
                {
                    b.Property<string>("UOMID")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("LinkedUOM")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Createdby")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal?>("Factor")
                        .HasColumnType("numeric(28, 8)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<byte?>("MultiplyDivide")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("RecordSource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("buid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValueSql("('1')");

                    b.HasKey("UOMID", "LinkedUOM");

                    b.ToTable("HH_IC_UOMDetail", (string)null);
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.HH_Item", b =>
                {
                    b.Property<string>("ItemNo")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("AssetLocationType")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<byte?>("AssignBatchOnReturn")
                        .HasColumnType("tinyint");

                    b.Property<string>("Attribute1Val")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("AttributeVal")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool?>("AutomaticCutQty")
                        .HasColumnType("bit");

                    b.Property<byte>("BatchSupport")
                        .HasColumnType("tinyint");

                    b.Property<string>("BrandNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte?>("CWItem")
                        .HasColumnType("tinyint");

                    b.Property<string>("CategoryID")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Createdby")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DamagedReturnItemId")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("DefaultUOM")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DefaultVendor")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<byte?>("EnableReturn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("((1))");

                    b.Property<int?>("GLDimensionSetID")
                        .HasColumnType("int");

                    b.Property<string>("GroupID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("InventoryTransactionUOM")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ItemConstraintID")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ItemNameA")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ItemNameE")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ItemType")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("LargeUOM")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MasterBrandID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("MaxQty")
                        .HasColumnType("numeric(28, 8)");

                    b.Property<string>("MaxQtyUOM")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal?>("MinQty")
                        .HasColumnType("numeric(28, 8)");

                    b.Property<decimal?>("MinimumStockPCT")
                        .HasColumnType("numeric(28, 8)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<int?>("PLT_CRT")
                        .HasColumnType("int");

                    b.Property<int?>("Packet_PLT")
                        .HasColumnType("int");

                    b.Property<decimal?>("PalletQuantity")
                        .HasColumnType("numeric(28, 8)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("PurchaseUOM")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<byte?>("RecordSource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("((0))");

                    b.Property<bool?>("ReturnDamaged")
                        .HasColumnType("bit");

                    b.Property<int?>("ReturnPercentageAfterShelfLife")
                        .HasColumnType("int");

                    b.Property<int?>("ReturnPercentageBeforeShelfLife")
                        .HasColumnType("int");

                    b.Property<int?>("ReturnPeriod")
                        .HasColumnType("int");

                    b.Property<int?>("ReturnQuantity")
                        .HasColumnType("int");

                    b.Property<string>("ReturnUOM")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SalesUOM")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("SecUOMQty")
                        .HasColumnType("numeric(28, 8)");

                    b.Property<byte>("SerialNumberSupport")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ShelfLife")
                        .HasColumnType("int");

                    b.Property<string>("ShortNameA")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ShortNameE")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SmallUOM")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TaxCodeID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("TaxExempted")
                        .HasColumnType("tinyint");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<bool>("ZeroCostPrice")
                        .HasColumnType("bit");

                    b.Property<bool>("ZeroSalePrice")
                        .HasColumnType("bit");

                    b.Property<string>("barcode1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("barcode2")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValueSql("(1)");

                    b.Property<string>("buid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValueSql("('1')");

                    b.HasKey("ItemNo");

                    b.HasIndex(new[] { "MasterBrandID" }, "idx_hh_item_masterBrandID");

                    b.ToTable("HH_Item", (string)null);
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.HH_ItemUoms", b =>
                {
                    b.Property<string>("ItemNo")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("SmallUOM")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("LargeUOM")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Createdby")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal?>("Factor")
                        .HasColumnType("numeric(28, 8)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<byte?>("MultiplyDivide")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("RecordSource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("buid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValueSql("('1')");

                    b.HasKey("ItemNo", "SmallUOM", "LargeUOM")
                        .HasName("PK_HH_hh_ItemUoms");

                    b.HasIndex(new[] { "ItemNo" }, "idx_hh_itemUoms_ItemNo");

                    b.ToTable("HH_ItemUoms");
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.HH_Messages", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageID"));

                    b.Property<string>("BUID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValueSql("('1')");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BranchNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Createdby")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<byte?>("SMS")
                        .HasColumnType("tinyint");

                    b.Property<string>("SalesManNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("SalesManType")
                        .HasColumnType("int");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime");

                    b.HasKey("MessageID");

                    b.ToTable("HH_Messages", t =>
                        {
                            t.HasTrigger("HH_Messages_delete_trigger");

                            t.HasTrigger("HH_Messages_insert_trigger");

                            t.HasTrigger("HH_Messages_update_trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.HH_PARAMS", b =>
                {
                    b.Property<int>("PARAM_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PARAM_ID"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PARAM_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PARAM_VALUE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("ParamControlType")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("PerBU")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("SystemParam")
                        .HasColumnType("tinyint");

                    b.HasKey("PARAM_ID");

                    b.ToTable("HH_PARAMS");
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.HH_PARAMS_BU", b =>
                {
                    b.Property<int>("PARAM_ID")
                        .HasColumnType("int");

                    b.Property<string>("BUID")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Createdby")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("PARAM_NAME")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PARAM_VALUE")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("PARAM_ID", "BUID");

                    b.ToTable("HH_PARAMS_BU", null, t =>
                        {
                            t.HasTrigger("HH_PARAMS_BU_delete_trigger");

                            t.HasTrigger("HH_PARAMS_BU_insert_trigger");

                            t.HasTrigger("HH_PARAMS_BU_update_trigger");

                            t.HasTrigger("Param7041_TempCreditValidations_HH_PARAMS_BU");

                            t.HasTrigger("UpdateParamValue_BU");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.HH_SA_BU", b =>
                {
                    b.Property<string>("BUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyGlAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultWarehouse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERPDistChannelID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERPOrganizationID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERPSalesDivisonID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("HasChildren")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint");

                    b.Property<string>("MemoLineId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("OrganizationType")
                        .HasColumnType("tinyint");

                    b.Property<string>("ParentBU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAPCompanyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAPCreditControlArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAPCreditSegment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAPGovernorate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAPSalesOffice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAPSalesOrg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAPSalesdistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAPplant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesTypeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TemporaryCredit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte?>("TypeOfPayment")
                        .HasColumnType("tinyint");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BUID");

                    b.ToTable("HH_SA_BU");
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.HH_SA_Role", b =>
                {
                    b.Property<string>("RoleID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("NeedExplicitUpdatePermission")
                        .HasColumnType("tinyint");

                    b.HasKey("RoleID");

                    b.ToTable("HH_SA_Roles");
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.HH_SA_RolePermission", b =>
                {
                    b.Property<string>("RoleID")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("KeyID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("CanAddAttachments")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("CanDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("((0))");

                    b.Property<byte?>("CanDeleteAttachments")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("CanExecute")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("((0))");

                    b.Property<byte?>("CanInsert")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("((0))");

                    b.Property<byte?>("CanRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("((0))");

                    b.Property<byte?>("CanUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("((0))");

                    b.Property<byte?>("CanViewAttachments")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Createdby")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.HasKey("RoleID", "KeyID")
                        .HasName("PK__HH_SA_RolePermis__341D6548");

                    b.ToTable("HH_SA_RolePermissions");
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.HH_SA_SecurityKey", b =>
                {
                    b.Property<string>("KeyID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Createdby")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DescriptionA")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("EnableEditOnERPIntegration")
                        .HasColumnType("tinyint");

                    b.Property<byte>("IsErpAware")
                        .HasColumnType("tinyint");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("ModuleDesc")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ModuleID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ParentKeyID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RedirectURI")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte?>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("KeyID")
                        .HasName("PK__HH_SA_SecurityKe__35118981");

                    b.ToTable("HH_SA_SecurityKeys");
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.HH_SA_UserBUPermissions", b =>
                {
                    b.Property<string>("UserID")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("BUID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValueSql("('1')");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Createdby")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.HasKey("UserID", "BUID")
                        .HasName("PK__HH_SA_UserBUPerm__1FF7A424");

                    b.ToTable("HH_SA_UserBUPermissions");
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.HH_Salesman", b =>
                {
                    b.Property<string>("SalesmanNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("AllowCreditOverride")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("AllowOnlineClose")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("AllowOnlineConfirm")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("AllowOnlineEdit")
                        .HasColumnType("tinyint");

                    b.Property<int?>("AllowOnlineReturn")
                        .HasColumnType("int");

                    b.Property<byte?>("AllowPriceEdit")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("AllowTwoActiveTrips")
                        .HasColumnType("tinyint");

                    b.Property<string>("AssignedDriverID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Book1End")
                        .HasColumnType("int");

                    b.Property<int>("Book1Start")
                        .HasColumnType("int");

                    b.Property<int>("Book2End")
                        .HasColumnType("int");

                    b.Property<int>("Book2Start")
                        .HasColumnType("int");

                    b.Property<int>("BookSizeMult")
                        .HasColumnType("int");

                    b.Property<string>("BranchNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CalendarID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CashJournalNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CashReceiptMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChequeJournalNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChequeReceiptMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommissionSchemeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("CommissionType")
                        .HasColumnType("tinyint");

                    b.Property<double?>("CommissionValue")
                        .HasColumnType("float");

                    b.Property<double>("ConsumptionFactor")
                        .HasColumnType("float");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditCardAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditCardReceiptMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CurrentOutOfRoute")
                        .HasColumnType("int");

                    b.Property<string>("DamagedWarehouse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultCustomerNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultMSL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultTerritory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("DisableDayofvisitedit")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("DisableLoadWithBalance")
                        .HasColumnType("tinyint");

                    b.Property<string>("Driver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERP_Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("EnableAutoArrive")
                        .HasColumnType("tinyint");

                    b.Property<int?>("EnableManualDiscountOnOrderLine")
                        .HasColumnType("int");

                    b.Property<byte?>("EnableOrderWithoutPOV")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EnablePrePayment")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EnableProforma")
                        .HasColumnType("tinyint");

                    b.Property<string>("EncPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GPSMinTrackingDist")
                        .HasColumnType("int");

                    b.Property<int?>("GPSMinTrackingTime")
                        .HasColumnType("int");

                    b.Property<byte?>("HWsupport")
                        .HasColumnType("tinyint");

                    b.Property<string>("HashPass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Helper1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Helper2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Helper3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("IgnoreCheckingPendingTransactions")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Inactive")
                        .HasColumnType("tinyint");

                    b.Property<byte>("IsParent")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsUser")
                        .HasColumnType("bit");

                    b.Property<int?>("JPCustCount")
                        .HasColumnType("int");

                    b.Property<string>("LanguageID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastPasswordRenew")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("LoadingLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MainWarehouseSellableBINLocation")
                        .HasColumnType("int");

                    b.Property<byte?>("MaxOfflineInvoices")
                        .HasColumnType("tinyint");

                    b.Property<int?>("MaxVisitsWithoutProof")
                        .HasColumnType("int");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Mode")
                        .HasColumnType("tinyint");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NextCustLocUpdateNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NextOrderNo")
                        .HasColumnType("int");

                    b.Property<int>("NextPaymentNo")
                        .HasColumnType("int");

                    b.Property<int?>("NextRequestNo")
                        .HasColumnType("int");

                    b.Property<int?>("NextReturnNo")
                        .HasColumnType("int");

                    b.Property<int>("NextVisitNo")
                        .HasColumnType("int");

                    b.Property<decimal?>("OpenInvoicesAmountLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OpenInvoicesCountLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OrderTakerSuggestedValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OutofOrderLimit")
                        .HasColumnType("int");

                    b.Property<decimal?>("OverDueInvoicesAmountLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OverDueInvoicesCountLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("OverduePendingPaymentsDays")
                        .HasColumnType("int");

                    b.Property<string>("ParentEmployee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentSalesmanID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PayBook1End")
                        .HasColumnType("int");

                    b.Property<int>("PayBook1Start")
                        .HasColumnType("int");

                    b.Property<int>("PayBook2End")
                        .HasColumnType("int");

                    b.Property<int>("PayBook2Start")
                        .HasColumnType("int");

                    b.Property<byte?>("Permission")
                        .HasColumnType("tinyint");

                    b.Property<string>("PreFix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("PreferredLanguage")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("ProofOfVisit")
                        .HasColumnType("tinyint");

                    b.Property<string>("RebateDocumentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("RecQtyCalcType")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("RecordSource")
                        .HasColumnType("tinyint");

                    b.Property<string>("ReplenishmentTemplateID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("ReturnType")
                        .HasColumnType("tinyint");

                    b.Property<string>("ReturnWarehouse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("RouteOrigin")
                        .HasColumnType("tinyint");

                    b.Property<int?>("SMDistanceRange")
                        .HasColumnType("int");

                    b.Property<string>("SMSTemplateTypeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SalesManType")
                        .HasColumnType("int");

                    b.Property<byte?>("SalesbuzzMobileClient")
                        .HasColumnType("tinyint");

                    b.Property<string>("SalesmanNameA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesmanNameE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StopDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("StopReasonID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuperVisorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuperVisorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("SyncBeforeVisit")
                        .HasColumnType("tinyint");

                    b.Property<string>("Tel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TemporaryCredit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TemporaryCreditBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransferPriceID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransferReceiptMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("UploadAfterVisit")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("UploadTruckNoToERP")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("UseNewPrintFW")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("VanIndicator")
                        .HasColumnType("tinyint");

                    b.Property<string>("WareHouse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("mandatoryStockCheckPhoto")
                        .HasColumnType("tinyint");

                    b.Property<int?>("outOfRouteLimit")
                        .HasColumnType("int");

                    b.Property<byte?>("preventcollect")
                        .HasColumnType("tinyint");

                    b.HasKey("SalesmanNo");

                    b.ToTable("HH_Salesman");
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.SA_AuditLog", b =>
                {
                    b.Property<long>("Serial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Serial"));

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<string>("NewData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Olddata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Operationtype")
                        .HasColumnType("tinyint");

                    b.Property<string>("TableKeys")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Serial");

                    b.ToTable("SA_AuditLogs");
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.SA_License", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EncryptedXmlData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SA_License");
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.SA_Session", b =>
                {
                    b.Property<Guid>("JTI")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("LastAccess")
                        .HasColumnType("datetime");

                    b.Property<string>("MachineIP")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte?>("S")
                        .HasColumnType("tinyint");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("JTI")
                        .HasName("PK__SA_Sessi__C4D18800571AE969");

                    b.ToTable("SA_Sessions");
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.ST_EventDefinition", b =>
                {
                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<short>("Eventlangid")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Createdby")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("EventText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte>("EventType")
                        .HasColumnType("tinyint");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.HasKey("EventID", "Eventlangid")
                        .HasName("PK__ST_EventDefiniti__2CDE666E");

                    b.ToTable("ST_EventDefinition", (string)null);
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.ST_EventLogDetail", b =>
                {
                    b.Property<decimal>("ProcessID")
                        .HasColumnType("decimal(15, 0)");

                    b.Property<decimal>("EventSerialNo")
                        .HasColumnType("decimal(15, 0)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Createdby")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("EventDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Var1")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Var10")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Var2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Var3")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Var4")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Var5")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Var6")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Var7")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Var8")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Var9")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ProcessID", "EventSerialNo")
                        .HasName("PK__ST_EventLogDetai__31A31B8B");

                    b.ToTable("ST_EventLogDetail", (string)null);
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.ST_EventLogMaster", b =>
                {
                    b.Property<decimal>("ProcessID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15, 0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ProcessID"));

                    b.Property<string>("ArabicDescription")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("BUID")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Createdby")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Description")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<byte?>("IsBatchJob")
                        .HasColumnType("tinyint");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("NTUserName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte?>("OverAllStatus")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("ProcessEnd")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ProcessStart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SQLUserName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("UserId")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("WorkStationName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("ProcessID")
                        .HasName("PK__ST_EventLogMaste__2EC6AEE0");

                    b.ToTable("ST_EventLogMaster", (string)null);
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.hh_ST_NumberSequance", b =>
                {
                    b.Property<string>("NumberSequanceID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ContinuousSequence")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Createdby")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DescriptionAR")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("ForceFormat")
                        .HasColumnType("tinyint");

                    b.Property<string>("Format")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IncrementBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<long?>("MaxValue")
                        .HasColumnType("bigint");

                    b.Property<long?>("MinValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<long?>("NextValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("((1))");

                    b.Property<byte?>("SerialLength")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("SerialStart")
                        .HasColumnType("tinyint");

                    b.HasKey("NumberSequanceID")
                        .HasName("PK__hh_ST_NumberSequ__49EDDDF0");

                    b.ToTable("hh_ST_NumberSequance", (string)null);
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.hh_ST_NumberSequanceCanceledSerials", b =>
                {
                    b.Property<string>("NumberSequanceID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("CanceledSerial")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Createdby")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.HasKey("NumberSequanceID", "CanceledSerial")
                        .HasName("PK__hh_ST_NumberSequ__4AE20229");

                    b.ToTable("hh_ST_NumberSequanceCanceledSerials");
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.hh_ST_NumberSequanceCanceledSerialsBU", b =>
                {
                    b.Property<string>("ShortCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<long>("CanceledSerial")
                        .HasColumnType("bigint");

                    b.Property<string>("NumberSequanceID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Createdby")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.HasKey("ShortCode", "CanceledSerial", "NumberSequanceID");

                    b.ToTable("hh_ST_NumberSequanceCanceledSerialsBU", (string)null);
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.hh_ST_NumberSequenceBU", b =>
                {
                    b.Property<string>("NumberSequanceID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShortCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Createdby")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<long?>("NextValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("NumberSequanceID", "ShortCode")
                        .HasName("PK_hh_ST_NumberSequenceBU_1");

                    b.ToTable("hh_ST_NumberSequenceBU", (string)null);
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.hh_Target", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("DisplayOrder")
                        .HasColumnType("smallint");

                    b.Property<bool>("HasDetail")
                        .HasColumnType("bit");

                    b.Property<bool?>("ISCalculated")
                        .HasColumnType("bit");

                    b.Property<bool?>("ISPercentage")
                        .HasColumnType("bit");

                    b.Property<byte?>("IsVisible")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("ItemBased")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestRefID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurveyRefId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("isCustomer")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("isDistributor")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("hh_Target");
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.loginusers", b =>
                {
                    b.Property<string>("userName")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<byte>("ADAuthentication")
                        .HasColumnType("tinyint");

                    b.Property<string>("ADUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("AdvancedWFUser")
                        .HasColumnType("tinyint");

                    b.Property<string>("BUID")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("EnableMFA")
                        .HasColumnType("tinyint");

                    b.Property<string>("EncPassword")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("ForceLogin")
                        .HasColumnType("tinyint");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("InActive")
                        .HasColumnType("tinyint");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastPasswordRenew")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleID")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("SupervisorModuleUser")
                        .HasColumnType("tinyint");

                    b.Property<bool>("WillNotExpired")
                        .HasColumnType("bit");

                    b.Property<string>("WindowsLogin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branchNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("password")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("role")
                        .HasColumnType("int");

                    b.Property<string>("userCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userName");

                    b.ToTable("loginusers");
                });

            modelBuilder.Entity("SalesBuzz.Shared.Models.RecordLevelSecurity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte>("RecType")
                        .HasColumnType("tinyint");

                    b.Property<string>("UserOrRoleID")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "UserOrRoleID", "RecType", "EntityName", "FieldName" }, "IX_RecordLevelSecurity")
                        .IsUnique();

                    b.ToTable("RecordLevelSecurity", (string)null);
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.ST_EventLogDetail", b =>
                {
                    b.HasOne("SalesBuzz.Shared.Entities.ST_EventLogMaster", "Process")
                        .WithMany("ST_EventLogDetails")
                        .HasForeignKey("ProcessID")
                        .IsRequired()
                        .HasConstraintName("FK_ST_EventLogDetail__ST_EventLogMaster__ProcessID");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("SalesBuzz.Shared.Entities.ST_EventLogMaster", b =>
                {
                    b.Navigation("ST_EventLogDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
